SELL = "SELL"
BUY = "BUY" 
NUll = "NULL"
USERPROMPT = "USERPROMPT"
GETORDERS  = "getOrders"
HOLDINGS = "holdings"
SELLORDER = "sellOrder"
BUYORDER = "buyOrder"
GEMINI_API_KEY = "AIzaSyBo2hVplFeqBWX_92hBTF5TwukVOXcD6oQ"
ANALYZE_PORTFOLIO  ="analyzePortfolio"
CANCELORDER = "cancelOrder"
CANCELALLORDERS = "cancelAllOrders"
UNKNOWN ="unknown"
MONGO_URL = "mongodb+srv://javedahmeddone:Mongo123@cluster0.solvgdq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"